### PR TITLE
0.1.0: BoOTs will fix ***everything***

### PR DESCRIPTION
**Pull request by Alastors**
It's just some bug fixes.

1. Fixes the researches.
2. Fixes the recipes
3. Shards still broken, that's GTNH's fault though need to figure out what's causing it because it doesn't happen outside the pack
4. Fixes the electric boots not crafting and the electric void from repairing itself
5. Gives the boots protection

### CODE REVIEW

**Comment by miozune** [comment]
- Grab [.gitignore](https://github.com/GTNewHorizons/ExampleMod1.7.10/blob/master/.gitignore) from ExampleMod repo and remove `run` folder
- Is `javaw_4cD9CjyTxN.gif` really needed?
- Update PR title, it doesn't explain what it does

**Comment by Alastors** [comment]
> - Grab [.gitignore](https://github.com/GTNewHorizons/ExampleMod1.7.10/blob/master/.gitignore) from ExampleMod repo and remove `run` folder
> 
> - Is `javaw_4cD9CjyTxN.gif` really needed?
> 
> - Update PR title, it doesn't explain what it does
Haha yeah sorry happens every time, need to update those settings

**Comment by Alastors** [comment]
Updated the PR comments

**Comment by Alastors** [comment]
Fixed, dunno why that gif was in there, that was from a dupe report awhile back

**Comment by miozune** [comment]
- Remove `.idea/vcs.xml` as well
- Use ExampleMod version of `.gitignore` to prevent accidental push in the future
- Isn't the term `TB` already used by ThaumicBases? It can be confusing

**Comment by Alastors** [comment]
> - Remove `.idea/vcs.xml` as well


Aight gimme a sec.


> - Use ExampleMod version of `.gitignore` to prevent accidental push in the future

I did?

> - Isn't the term `TB` already used by ThaumicBases? It can be confusing

Yeah, alternatively I could use TBoots, but honestly, I don't think it would matter overall, it's internal names, 99% of the players won't even know it exists. But I can change it if you think it's that important?

**Comment by miozune** [comment]
> I did?

No, check your branch

> Yeah, alternatively I could use TBoots, but honestly, I don't think it would matter overall, it's internal names, 99% of the players won't even know it exists. But I can change it if you think it's that important?

Well not that critical

**Review by miozune — APPROVED** [review]

**Pull request merged**
